package com.onlyone.crm.settings.domain;

import java.util.Objects;

public class DicValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.id
     *
     * @mbggenerated Fri Dec 01 14:34:04 CST 2023
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.value
     *
     * @mbggenerated Fri Dec 01 14:34:04 CST 2023
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.text
     *
     * @mbggenerated Fri Dec 01 14:34:04 CST 2023
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.orderNo
     *
     * @mbggenerated Fri Dec 01 14:34:04 CST 2023
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.typeCode
     *
     * @mbggenerated Fri Dec 01 14:34:04 CST 2023
     */
    private String typeCode;

    @Override
    public String toString() {
        return "DicValue{" +
                "id='" + id + '\'' +
                ", value='" + value + '\'' +
                ", text='" + text + '\'' +
                ", orderNo='" + orderNo + '\'' +
                ", typeCode='" + typeCode + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DicValue dicValue = (DicValue) o;
        return Objects.equals(id, dicValue.id) && Objects.equals(value, dicValue.value) && Objects.equals(text, dicValue.text) && Objects.equals(orderNo, dicValue.orderNo) && Objects.equals(typeCode, dicValue.typeCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, value, text, orderNo, typeCode);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public DicValue() {
    }

    public DicValue(String id, String value, String text, String orderNo, String typeCode) {
        this.id = id;
        this.value = value;
        this.text = text;
        this.orderNo = orderNo;
        this.typeCode = typeCode;
    }
}
